### ISSUE TITLE
aria2c cannot find many magnet links, but uTorrent work fine, why ?

### ISSUE THREAD

**Issue by Denisov39** [tatsuhiro-t/aria2#343]
Hi !
I try to download this magnet (for example)
magnet:?xt=urn:btih:62493696a150819a17f5c8dc9c876c44843968a1&dn=Game%20of%20Thrones

In log i see this

2015-02-20 13:24:56.579034 [DEBUG] [DHTMessageDispatcherImpl.cc:112] 0 dht messages remaining in the queue.
2015-02-20 13:24:56.579169 [DEBUG] [DHTGetPeersCommand.cc:106] Issuing PeerLookup for infoHash=62493696a150819a17f5c8dc9c876c44843968a1
[#0689a8 0B/0B CN:0 SD:0 DL:0B]2015-02-20 13:24:57.580340 [DEBUG] [DHTTaskQueueImpl.cc:56] Updating periodicTaskQueue1     
2015-02-20 13:24:57.580372 [DEBUG] [DHTTaskExecutor.cc:75] Executing 0 Task(s). Queue has 0 task(s).
2015-02-20 13:24:57.580384 [DEBUG] [DHTTaskQueueImpl.cc:58] Updating periodicTaskQueue2

But my uTorrent client download this magnet.

Why aria2 not downloading this ?

Regards, Pavel.

**Comment by rabbitsmith** [comment]
same problem here. somebody please help us.

**Comment by mouradski** [comment]
same problem :( 
when i download a .torrent file from kick ass, it works, but the magnet lik of the same torrent never starts download and seed = 0

help please

**Comment by dofine** [comment]
Same problem ...

**Comment by mouradski** [comment]
Fixed : add --follow-torrent=mem option :)

**Comment by scytalezero** [comment]
I am having this problem as well and have tested with several magnets that worked fine in qBittorrent. Adding the "follow-torrent=mem" option did not solve the problem for me.

**Comment by tatsuhiro-t** [comment]
I have fixed UDP tracker bug, which prevents aria2 from getting peers from UDP tracker.  Try master branch, or wait for the next release.
