### ISSUE TITLE
Aria2 sometimes hangs during downloading several files

### ISSUE THREAD

**Issue by scytalezero** [tatsuhiro-t/aria2#441]
So I don't know if this is an issue with Aria2, or an environmental issue of mine. I've tried reverting to earlier versions of Aria2 with no luck. To recreate this problem, it usually works for me to download a number of videos from Youtube so that I have some simultaneous downloads (currently set to 3) and some waiting. At some point in this process Aria2 will sometimes become non-responsive and consume an entire CPU core. When this happens the console window (I run it in rpc mode) just freezes and I have to terminate the process.

I'm still trying to isolate when this happens, but it doesn't seem to occur unless it's simultaneous downloads of larger files.

I'm attaching the tail of a debug log from the last time this happened. If anybody has any ideas they would be greatly appreciated. This just started happening fairly recently and I'm not sure what changed on my end.

**Comment by scytalezero** [comment]
Here are the last moments of the log file before the process ran away:

2015-08-03 23:24:20.865082 [DEBUG] [WrDiskCacheEntry.cc:96] WrDiskCacheEntry cache goff=266238728, len=16384
2015-08-03 23:24:20.865082 [DEBUG] [WrDiskCache.cc:100] Update cache entry size=965384, delta=16384, clock=196378
2015-08-03 23:24:20.865082 [DEBUG] [AbstractCommand.cc:187] CUID#1339 - socket: read:1, write:0, hup:0, err:0
2015-08-03 23:24:20.865082 [DEBUG] [WinTLSSession.cc:452] WinTLS: Read request: 16384 buffered: 4067
2015-08-03 23:24:20.865082 [DEBUG] [Piece.cc:356] updateWrCache entry=0000000002116520
2015-08-03 23:24:20.865082 [DEBUG] [WrDiskCacheEntry.cc:96] WrDiskCacheEntry cache goff=266255112, len=16384
2015-08-03 23:24:20.865082 [DEBUG] [WrDiskCache.cc:100] Update cache entry size=981768, delta=16384, clock=196379
2015-08-03 23:24:20.865082 [DEBUG] [AbstractCommand.cc:187] CUID#1339 - socket: read:1, write:0, hup:0, err:0
2015-08-03 23:24:20.865082 [DEBUG] [WinTLSSession.cc:452] WinTLS: Read request: 16384 buffered: 4067
2015-08-03 23:24:20.865082 [DEBUG] [Piece.cc:356] updateWrCache entry=0000000002116520
2015-08-03 23:24:20.865082 [DEBUG] [WrDiskCacheEntry.cc:96] WrDiskCacheEntry cache goff=266271496, len=16384
2015-08-03 23:24:20.865082 [DEBUG] [WrDiskCache.cc:100] Update cache entry size=998152, delta=16384, clock=196380
2015-08-03 23:24:20.865082 [DEBUG] [AbstractCommand.cc:187] CUID#1339 - socket: read:1, write:0, hup:0, err:0
2015-08-03 23:24:20.865082 [DEBUG] [WinTLSSession.cc:452] WinTLS: Read request: 16384 buffered: 4067
2015-08-03 23:24:20.865082 [DEBUG] [Piece.cc:356] updateWrCache entry=0000000002116520
2015-08-03 23:24:20.865082 [DEBUG] [WrDiskCacheEntry.cc:96] WrDiskCacheEntry cache goff=266287880, len=16384
2015-08-03 23:24:20.865082 [DEBUG] [WrDiskCache.cc:100] Update cache entry size=1014536, delta=16384, clock=196381
2015-08-03 23:24:20.865082 [DEBUG] [AbstractCommand.cc:187] CUID#1339 - socket: read:1, write:0, hup:0, err:0
2015-08-03 23:24:20.865082 [DEBUG] [WinTLSSession.cc:452] WinTLS: Read request: 16384 buffered: 4067
2015-08-03 23:24:20.865082 [DEBUG] [Piece.cc:356] updateWrCache entry=0000000002116520
2015-08-03 23:24:20.865082 [DEBUG] [WrDiskCacheEntry.cc:96] WrDiskCacheEntry cache goff=266304264, len=16384
2015-08-03 23:24:20.865082 [DEBUG] [WrDiskCache.cc:100] Update cache entry size=1030920, delta=16384, clock=196382
2015-08-03 23:24:20.865082 [DEBUG] [AbstractCommand.cc:187] CUID#1339 - socket: read:1, write:0, hup:0, err:0
2015-08-03 23:24:20.865082 [DEBUG] [WinTLSSession.cc:452] WinTLS: Read request: 16384 buffered: 4067
2015-08-03 23:24:20.866082 [DEBUG] [WinTLSSession.cc:513] WinTLS: Connection abruptly closed!
2015-08-03 23:24:20.866082 [DEBUG] [WinTLSSession.cc:193] WinTLS: Closing connection
2015-08-03 23:24:20.866082 [DEBUG] [WinTLSSession.cc:301] WinTLS: Write request: 31 buffered: 0

**Comment by scytalezero** [comment]
I've been playing with my settings to see what I might have changed that started this issue occurring. After playing around with file allocation and some other settings, I found that after commenting this line in my config I cannot reproduce the hang:

max-overall-download-limit=3M

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  This probably comes from some bug in rate throttling code. I'll look into it.

**Comment by scytalezero** [comment]
No, thank you. Did I mention that I love Aria2? It really is awesome, especially for people like me that do lots of scripting and automation. The RPC interface is super - I have it integrated into my home automation UI and can easily send downloads to it from anywhere. The event hooks let me run a script that renames and categorizes things on my server. This is actually the first time I've ever noticed any bug in Aria2 at all, and I use the hell out of it.

Anyway, I just wanted to say thanks for the time you spend on this awesome utility.

**Comment by tatsuhiro-t** [comment]
I have not reproduced this issue, but found the code which potentially causes busy loop.
Fix was committed via 925b5ce

**Comment by nmaier** [comment]
Yeah, @tatsuhiro-t the fix looks about right

**Comment by scytalezero** [comment]
Thanks for the fast response!

**Comment by scytalezero** [comment]
I installed the latest release and did some testing today. So far I'm not able to recreate the loop after re-enabling max-overall-download-limit, so I'm closing this issue.

**Comment by scytalezero** [comment]
Sorry to say that I am still experiencing this problem. It definitely only happens when I have max-overall-download-limit set in my config.

**Comment by tatsuhiro-t** [comment]
Are you experiencing this issue with only HTTPS URIs?  Or do you think HTTP URIs also produce this issue?

**Comment by scytalezero** [comment]
I have only seen this happen with HTTPS, but that is mostly what I download through Aria2.

**Comment by tatsuhiro-t** [comment]
Thank you.  I still could not reproduce this issue.  I found a problem related to WinTLS, but it probably does not cause busy loop.
Could you show us how to easily reproduce this issue?

**Comment by tatsuhiro-t** [comment]
The bug mentioned in the previous post was fixed by the comment cf2fa33fe0d73f7001d262beee5e8aba03544126.
This bug may cause hang when download HTTPS URI, but without busy loop.  If this symptom is the same one you experienced, then this is the bug we are looking for.

**Comment by scytalezero** [comment]
As of the latest release, I am still experiencing this issue. For reproduction, I suggest the following:

1) Set 'max-overall-download-limit' in your config file to some percentage of your full bandwidth.
2) Allow for a few concurrent downloads (I use 3).
2) Run Aria2 in RPC listen mode.
3) Throw a lot of Youtube video links at it. They will all be HTTPS. At some point during the process, Aria2 will likely enter a loop and become unresponsive.

**Comment by tatsuhiro-t** [comment]
Thank you for heads up.  Will do more testing.  My windows environment is quite poor, and very slow, so it might not catch the bug.
If anyone has descent Windows build environment and successfully reproduced this issue, please do some debugging and find the cause.  We are very appreciated for that.

**Comment by tatsuhiro-t** [comment]
BTW, which windows version are you using?  64 or 32-bit?

**Comment by scytalezero** [comment]
I'm on Windows Server 2012 R2 x64.

**Comment by tatsuhiro-t** [comment]
Thank you. I was talking about aria2 binary, but probably my words were quite ambiguous.  We are distributing 2 binaries 64 bit aria2 and 32 bit aria2.  32 bit aria2 can run both 32 bit windows and 64 bit windows.  Which aria2 binary are you using?

**Comment by scytalezero** [comment]
Oh sorry! I am using aria2 x64.

**Comment by tatsuhiro-t** [comment]
Thank you. I will do test with aria2 64-bit version.

**Comment by rc4991** [comment]
Hi Folks. Has there been any progress on this issue? 
I also see this issue with 64 bit when using max-overall-download-limit option.
Any recommended alternative (other then not setting a limit)?
Thanks.

**Comment by tatsuhiro-t** [comment]
As far as I know, there is no news about this issue.
Are you experience with this issue with plain HTTP?  Or only with HTTPS?
max-overall-download-limit is the only way to throttle across entire aria2 instance.

**Comment by scytalezero** [comment]
Personally I've had to discontinue using max-overall-download-limit.

**Comment by rc4991** [comment]
I'd have to check on if the issue is with HTTP as well. I would think WinTLS is not really involved in HTTP, but I'm no expert.

Has anyone tried the per download throttling approach? does that also suffer similar issue?
R
